# Generated by Django 5.0.3 on 2024-05-31 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'America'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
            ],
            options={
                'db_table': 'teacher_registration',
            },
        ),
    ]
