# Generated by Django 5.0.3 on 2024-06-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_model',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
