# Generated by Django 5.0.3 on 2024-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_registration_model_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_model',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
