# Generated by Django 5.0.3 on 2024-06-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_registration_model_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_model',
            old_name='name',
            new_name='teacher_name',
        ),
    ]
