# Generated by Django 5.0.3 on 2024-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_rename_name_registration_model_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_model',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration_model',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration_model',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration_model',
            name='teacher_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
