# Generated by Django 5.0.3 on 2024-06-16 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_registration_model_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_marks_register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField(max_length=3, null=True)),
                ('english', models.IntegerField(max_length=3, null=True)),
                ('maths', models.IntegerField(max_length=3, null=True)),
                ('science', models.IntegerField(max_length=3, null=True)),
                ('social', models.IntegerField(max_length=3, null=True)),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('status', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'db_table': 'student_marks_register',
            },
        ),
    ]
