# Generated by Django 5.0.3 on 2024-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_student_marks_register_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks_register_model',
            name='english',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_marks_register_model',
            name='maths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_marks_register_model',
            name='science',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_marks_register_model',
            name='social',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_marks_register_model',
            name='tamil',
            field=models.IntegerField(null=True),
        ),
    ]
