# Generated by Django 5.0.3 on 2024-06-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_student_marks_register_model_english_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration_model',
        ),
        migrations.DeleteModel(
            name='student_marks_register_model',
        ),
    ]
