# Generated by Django 5.0.3 on 2024-06-04 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prod_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('Description', models.TextField()),
                ('Product_stock', models.IntegerField(null=True)),
                ('Image', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('status', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'db_table': 'Product_Details',
            },
        ),
    ]
