# Generated by Django 5.0.3 on 2024-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_model',
            name='Mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
