# Generated by Django 5.0.3 on 2024-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Member', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Product Manager', 'Product Manager')], max_length=50)),
            ],
            options={
                'db_table': 'Login Form',
            },
        ),
    ]
