# Generated by Django 5.0.3 on 2024-06-11 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_registration_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Class', models.CharField(choices=[('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('profile', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('status', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'db_table': 'student_registration',
            },
        ),
    ]
