# Generated by Django 5.0.3 on 2024-06-12 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_stud_registration_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_registration_model',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='stud_registration_model',
            name='your_reister_no_is',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
