# Generated by Django 5.0.3 on 2024-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_stud_registration_model_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_model',
            name='Member',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin')], max_length=50),
        ),
    ]
