# Generated by Django 5.0.3 on 2024-06-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_login_model_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_registration_model',
            old_name='Class',
            new_name='Clas',
        ),
    ]
