# Generated by Django 5.0.3 on 2024-06-21 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_class_stud_registration_model_clas'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50, null=True)),
                ('mail', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'America'), ('other', 'Other')], max_length=50)),
                ('profile', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('status', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'db_table': 'teacher_registration',
            },
        ),
        migrations.CreateModel(
            name='student_marks_register_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.IntegerField(null=True)),
                ('tamil', models.IntegerField(null=True)),
                ('english', models.IntegerField(null=True)),
                ('maths', models.IntegerField(null=True)),
                ('science', models.IntegerField(null=True)),
                ('social', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('status', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'db_table': 'student_marks_register',
            },
        ),
    ]
