# Generated by Django 5.0.3 on 2024-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_registration_model_student_marks_register_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks_register_model',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student_marks_register_model',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
