# Generated by Django 5.0.3 on 2024-08-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_marks_register_model_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_marks_register_model',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='student_marks_register_model',
            name='total',
        ),
    ]
